INSERT INTO users (name, age) VALUES ("Dave", 28);
INSERT INTO users (name, age) VALUES ("Gina", 28);
INSERT INTO users (name, age) VALUES ("Derek", 29);
INSERT INTO users (name, age) VALUES ("Adriana", 23);
INSERT INTO users (name, age) VALUES ("Annais", 19);
INSERT INTO users (name, age) VALUES ("Tom", 65);
INSERT INTO users (name, age) VALUES ("Mark", 35);
INSERT INTO users (name, age) VALUES ("Jen", 37);
INSERT INTO users (name, age) VALUES ("Shawn", 31);
INSERT INTO users (name, age) VALUES ("Jared", 36);
INSERT INTO users (name, age) VALUES ("Amanda", 35);
INSERT INTO users (name, age) VALUES ("Owoose", 23);
INSERT INTO users (name, age) VALUES ("Randy", 39);
INSERT INTO users (name, age) VALUES ("Lisa", 38);
INSERT INTO users (name, age) VALUES ("Connor", 36);
INSERT INTO users (name, age) VALUES ("Hitomi", 37);
INSERT INTO users (name, age) VALUES ("Johnny", 34);
INSERT INTO users (name, age) VALUES ("Stephanie", 36);
INSERT INTO users (name, age) VALUES ("Peter", 31);
INSERT INTO users (name, age) VALUES ("Amanda", 32);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sleep Stopper", "Medical", 2000, "01/01/2020", "02/29/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cat Improver", "Pets", 1000000, "01/01/2020", "03/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Baseball Game Quicker Upper", "Sports", 150000, "02/01/2020", "04/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Red Sox Make-Betterer", "Sports", 5000000000, "01/01/2020", "12/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Zoolander School For Kids Who Can't Read Good", "Education", 5, "02/01/2020", "02/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Promote Dunder Millfin Paper", "Business", 25000, "03/01/2020", "03/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Library Renovation", "Education", 50000, "01/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New School Textbooks", "Education", 1500, "01/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Improve Baseball Field", "Community", 15000, "01/01/2020", "04/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Start Board Game Club", "Community", 100, "01/01/2020", "02/29/2020");